# Site settings
title: Flash Food!

# Footer content
email: flashfoodteam@gmail.com
twitter_username: FlashFoodTeam
github_username:  ufo2mstar
description:
#, &trade; ,
#&#8482;
#&#169; &copy; U+24B8 and (HTML &#9400;) and U+24D2 CIRCLED LATIN SMALL LETTER C (HTML &#9426;


baseurl: "/flashfood" # the subpath of your site, e.g. /blog/
url: "http://ufo2mstar.github.com" # the base hostname & protocol for your site


# for the snitcart!
api_key: YjdiNWIyOTUtZTIyMy00MWMwLTkwNDUtMzI1M2M2NTgxYjE0

# Build settings
markdown: rdiscount
rdiscount:
  extensions: [smart]

#permalink: /page/:title
collections:
  products:
    output: true.
